const arraySeasonalFruits =["Banana","Orange","Apple","Mango","Water melon"];
 console.log(arraySeasonalFruits);
 console.log(`------------------------------------------------------------------------------------`);
 console.log(`first fruit in the array is :${arraySeasonalFruits[0]}`);
 console.log(`------------------------------------------------------------------------------------`);
 console.log(`Last fruit in the array is :${arraySeasonalFruits[arraySeasonalFruits.length-1]}`);
 console.log(`------------------------------------------------------------------------------------`);
 console.log(`******** Adding papaya before element Banana   *******`);
 arraySeasonalFruits.unshift("papaya");
 console.log(arraySeasonalFruits);
 console.log(`------------------------------------------------------------------------------------`);
 console.log(`*********      Remove Mango form the array       ********`);
 arraySeasonalFruits.splice(4,1);
 console.log(arraySeasonalFruits);
 console.log(`------------------------------------------------------------------------------------`);
 console.log(`*********      Insert pineapple at last position      *********`);
 arraySeasonalFruits.push("pineapple");
 console.log(arraySeasonalFruits);
 console.log(`------------------------------------------------------------------------------------`);
 console.log(`**********     insert dragon fruit before water melon      ********`);
 arraySeasonalFruits.splice(4,0,"dragon fruit")
 console.log(arraySeasonalFruits);
 console.log(`------------------------------------------------------------------------------------`);
 console.log(`**********     Repalace Orange to  Kiwi    ***********`);
 arraySeasonalFruits.splice(2,1,"Kiwi");
 console.log(arraySeasonalFruits);
 console.log(`------------------------------------------------------------------------------------`);
 console.log(`first four element in the array are: ${arraySeasonalFruits.slice(0,4)}`);
 console.log(`------------------------------------------------------------------------------------`);
 const arrayLastFourFruits = arraySeasonalFruits.slice(arraySeasonalFruits.length-3 , arraySeasonalFruits.length);
 console.log(`Last three element in the array are :${arrayLastFourFruits}`);